### ISSUE TITLE
I get AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by miladf2** [Warflop/cloudbunny#9]
Traceback (most recent call last):
  File "cloudbunny.py", line 191, in <module>
    main()
  File "cloudbunny.py", line 111, in main
    title =	search(args.url).encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by Warflop** [comment]
I fixed issues and probably will work on some refactoring.
